# SPDX-License-Identifier: GPL-2.0-or-later
"""Built-in IEEE 1905.1 TLV implementations.

Importing this package registers every concrete TLV class with the
global :class:`~ieee1905.plugins.registry.TLVRegistry`, so the rest of
the codebase can decode wire TLVs into typed objects via
:func:`ieee1905.core.tlv.decode_raw`.
"""

from ieee1905.core.tlvs.ieee1905_1 import (
    AlMacAddress,
    AutoconfigFreqBand,
    DeviceInformation,
    EndOfMessage,
    LinkMetricResultCode,
    LocalInterface,
    MacAddress,
    NeighborDevice,
    NeighborEntry,
    ProfileVersion,
    SearchedRole,
    SupportedFreqBand,
    SupportedRole,
    VendorSpecific,
)
from ieee1905.core.tlvs.ieee1905_1_more import (
    BridgingTuple,
    ControlUrl,
    DeviceBridgingCapability,
    DeviceIdentification,
    GenericPhyDeviceInformation,
    GenericPhyEventEntry,
    GenericPhyEventNotification,
    GenericPhyInterface,
    InterfacePowerChangeEntry,
    InterfacePowerChangeInformation,
    InterfacePowerChangeStatus,
    IPv4,
    Ipv4Address,
    Ipv4Entry,
    IPv6,
    Ipv6Address,
    Ipv6Entry,
    L2LocalInterface,
    L2Neighbor,
    L2NeighborDevice,
    LinkMetricQuery,
    Non1905NeighborDeviceList,
    PbeMediaType,
    PowerOffInterface,
    PowerOffInterfaceEntry,
    PushButtonEventNotification,
    PushButtonJoinNotification,
    ReceiverLinkEntry,
    ReceiverLinkMetric,
    TransmitterLinkEntry,
    TransmitterLinkMetric,
    WscFrame,
)

__all__ = [
    "AlMacAddress",
    "AutoconfigFreqBand",
    "BridgingTuple",
    "ControlUrl",
    "DeviceBridgingCapability",
    "DeviceIdentification",
    "DeviceInformation",
    "EndOfMessage",
    "GenericPhyDeviceInformation",
    "GenericPhyEventEntry",
    "GenericPhyEventNotification",
    "GenericPhyInterface",
    "IPv4",
    "IPv6",
    "InterfacePowerChangeEntry",
    "InterfacePowerChangeInformation",
    "InterfacePowerChangeStatus",
    "Ipv4Address",
    "Ipv4Entry",
    "Ipv6Address",
    "Ipv6Entry",
    "L2LocalInterface",
    "L2Neighbor",
    "L2NeighborDevice",
    "LinkMetricQuery",
    "LinkMetricResultCode",
    "LocalInterface",
    "MacAddress",
    "NeighborDevice",
    "NeighborEntry",
    "Non1905NeighborDeviceList",
    "PbeMediaType",
    "PowerOffInterface",
    "PowerOffInterfaceEntry",
    "ProfileVersion",
    "PushButtonEventNotification",
    "PushButtonJoinNotification",
    "ReceiverLinkEntry",
    "ReceiverLinkMetric",
    "SearchedRole",
    "SupportedFreqBand",
    "SupportedRole",
    "TransmitterLinkEntry",
    "TransmitterLinkMetric",
    "VendorSpecific",
    "WscFrame",
]
