# SPDX-License-Identifier: GPL-2.0-or-later
"""IEEE 1905.1 TLV type identifiers.

Per IEEE 1905.1-2013 §17.2 (Table 17-2) and amendments. EasyMesh adds
many types in the 0x80+ range; those are introduced in Phase 2.
"""

from __future__ import annotations

from enum import IntEnum


class TLVType(IntEnum):
    """IEEE 1905.1 baseline TLV type identifiers."""

    END_OF_MESSAGE = 0x00
    AL_MAC_ADDRESS = 0x01
    MAC_ADDRESS = 0x02
    DEVICE_INFORMATION = 0x03
    DEVICE_BRIDGING_CAPABILITY = 0x04
    # 0x05 is reserved
    NON_1905_NEIGHBOR_DEVICE_LIST = 0x06
    NEIGHBOR_DEVICE = 0x07
    LINK_METRIC_QUERY = 0x08
    TRANSMITTER_LINK_METRIC = 0x09
    RECEIVER_LINK_METRIC = 0x0A
    VENDOR_SPECIFIC = 0x0B
    LINK_METRIC_RESULT_CODE = 0x0C
    SEARCHED_ROLE = 0x0D
    AUTOCONFIG_FREQ_BAND = 0x0E
    SUPPORTED_ROLE = 0x0F
    SUPPORTED_FREQ_BAND = 0x10
    WSC = 0x11
    PUSH_BUTTON_EVENT_NOTIFICATION = 0x12
    PUSH_BUTTON_JOIN_NOTIFICATION = 0x13
    GENERIC_PHY_DEVICE_INFORMATION = 0x14
    DEVICE_IDENTIFICATION = 0x15
    CONTROL_URL = 0x16
    IPV4 = 0x17
    IPV6 = 0x18
    GENERIC_PHY_EVENT_NOTIFICATION = 0x19
    PROFILE_VERSION = 0x1A
    POWER_OFF_INTERFACE = 0x1B
    INTERFACE_POWER_CHANGE_INFORMATION = 0x1C
    INTERFACE_POWER_CHANGE_STATUS = 0x1D
    L2_NEIGHBOR_DEVICE = 0x1E

    # ---- Wi-Fi EasyMesh R1 (Multi-AP Specification v1.0) -------------------
    # Spec: Multi-AP Specification v1.0 §17.2.x. Names follow the spec; the
    # ``EM_`` prefix keeps them distinct from 1905.1 baseline.

    EM_SUPPORTED_SERVICE = 0x80
    EM_SEARCHED_SERVICE = 0x81
    EM_AP_RADIO_IDENTIFIER = 0x82
    EM_AP_OPERATIONAL_BSS = 0x83
    EM_ASSOCIATED_CLIENTS = 0x84
    EM_AP_RADIO_BASIC_CAPABILITIES = 0x85
    EM_AP_HT_CAPABILITIES = 0x86
    EM_AP_VHT_CAPABILITIES = 0x87
    EM_AP_HE_CAPABILITIES = 0x88
    EM_STEERING_POLICY = 0x89
    EM_METRIC_REPORTING_POLICY = 0x8A
    EM_CHANNEL_PREFERENCE = 0x8B
    EM_RADIO_OPERATION_RESTRICTION = 0x8C
    EM_TRANSMIT_POWER_LIMIT = 0x8D
    EM_CHANNEL_SELECTION_RESPONSE = 0x8E
    EM_OPERATING_CHANNEL_REPORT = 0x8F
    EM_CLIENT_INFO = 0x90
    EM_CLIENT_CAPABILITY_REPORT = 0x91
    EM_CLIENT_ASSOCIATION_EVENT = 0x92
    EM_AP_METRIC_QUERY = 0x93
    EM_AP_METRICS = 0x94
    EM_STA_MAC_ADDRESS_TYPE = 0x95
    EM_ASSOCIATED_STA_LINK_METRICS = 0x96
    EM_UNASSOCIATED_STA_LINK_METRICS_QUERY = 0x97
    EM_UNASSOCIATED_STA_LINK_METRICS_RESPONSE = 0x98
    EM_BEACON_METRICS_QUERY = 0x99
    EM_BEACON_METRICS_RESPONSE = 0x9A
    EM_STEERING_REQUEST = 0x9B
    EM_STEERING_BTM_REPORT = 0x9C
    EM_CLIENT_ASSOCIATION_CONTROL_REQUEST = 0x9D
    EM_BACKHAUL_STEERING_REQUEST = 0x9E
    EM_BACKHAUL_STEERING_RESPONSE = 0x9F
    EM_HIGHER_LAYER_DATA = 0xA0
    EM_AP_CAPABILITY = 0xA1
    EM_ASSOCIATED_STA_TRAFFIC_STATS = 0xA2
    EM_ERROR_CODE = 0xA3

    # ---- Wi-Fi EasyMesh R2 (Multi-AP Specification v2.0) -------------------
    # Spec: Multi-AP Specification v2.0 §17.2.x.

    EM_CHANNEL_SCAN_REPORTING_POLICY = 0xA4
    EM_CHANNEL_SCAN_CAPABILITIES = 0xA5
    EM_CHANNEL_SCAN_REQUEST = 0xA6
    EM_CHANNEL_SCAN_RESULT = 0xA7
    EM_TIMESTAMP = 0xA8
    EM_1905_LAYER_SECURITY_CAPABILITY = 0xAA
    EM_PROFILE_2_AP_CAPABILITY = 0xAE
    EM_DEFAULT_8021Q_SETTINGS = 0xAF
    EM_TRAFFIC_SEPARATION_POLICY = 0xB0
    EM_PROFILE_2_ERROR_CODE = 0xBC
    EM_AP_RADIO_ADVANCED_CAPABILITIES = 0xBE
    EM_ASSOCIATION_STATUS_NOTIFICATION = 0xBF
    EM_SOURCE_INFO = 0xC0
    EM_TUNNELED_MESSAGE_TYPE = 0xC1
    EM_TUNNELED = 0xC2
    EM_PROFILE_2_STEERING_REQUEST = 0xC3
    EM_UNSUCCESSFUL_ASSOCIATION_POLICY = 0xC4
    EM_METRIC_COLLECTION_INTERVAL = 0xC5
    EM_RADIO_METRICS = 0xC6
    EM_AP_EXTENDED_METRICS = 0xC7
    EM_ASSOCIATED_STA_EXTENDED_LINK_METRICS = 0xC8
    EM_STATUS_CODE = 0xC9
    EM_REASON_CODE = 0xCA
    EM_BACKHAUL_STA_RADIO_CAPABILITIES = 0xCB
    EM_AKM_SUITE_CAPABILITIES = 0xCC

    @classmethod
    def describe(cls, value: int) -> str:
        try:
            return cls(value).name
        except ValueError:
            return f"Unknown(0x{value:02x})"
